# Generated by Django 4.2.13 on 2024-05-28 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosComplementarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Agregar el nombre de la empresa', max_length=60, unique=True, verbose_name='Razon_social')),
                ('nit', models.PositiveIntegerField(help_text='Agregar el nit de la empresa sin el codigo de verificacion y sin puntos', unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(help_text='Dirección donde se encuentra la empresa', max_length=255, verbose_name='Direccion')),
                ('pais', models.CharField(help_text='Pais donde se encuentra la empresa', max_length=60, verbose_name='Pais')),
                ('ubicacion', models.CharField(help_text='Hace referencia en que ciudad se encuentra la empresa', max_length=60, verbose_name='Ubicacion')),
                ('telefono', models.BigIntegerField(help_text='Numero de contacto a la que se puede llamar a la empresa', unique=True, verbose_name='Telefono')),
                ('pagina_web', models.URLField(blank=True, help_text='Pagina web de la empresa', null=True, unique=True, verbose_name='Pagina_web')),
                ('user', models.OneToOneField(help_text='Relacion con la tabla auth_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datos_complementarios',
                'db_table_comment': 'Tabla que complementa los datos de un usuario registrado, con datos adiccionales al de la tabla auth_user',
                'ordering': ['razon_social'],
            },
        ),
    ]
